### ISSUE TITLE
ArrayBuffer is stored in memory?

### ISSUE THREAD

**Issue by vj-abishek** [subins2000/simple-peer-files#1]
@subins2000 First of all thanks for this package. I noticed that you are storing ArrayBuffer in memory while transferring remotely, which isn't efficient. Do you have a better way? 

And also, noticed that you are using the promise 
` spf.send(peer, 'myFileID', file).then(transfer)`
But inside the promise, you are using events. In a react app it is causing issue. 

>maxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroy listeners added. Use emitter.setMaxListeners() to increase limit

If it uses events means, I can do something like this
```js
useEffect(() => {
    const update = (newData) => {
      setMessage([...message, newData])    
    }
    peer.on('data',  update)
  return () => peer.off('data', update);
  }, [message])
```
But I cannot off the event while unmounting, do you have any solution?

And also do you know anything regarding this issue https://github.com/feross/simple-peer/issues/748#issue-724332655

**Comment by vj-abishek** [comment]
found the answer to all of those, so closing this issue

**Comment by Jatinkabariya** [comment]
> found the answer to all of those, so closing this issue

what is the answer?
